name: Python Shell Script

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the action on
  pull_request:
    branches:
      - main  # Replace with the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest  # Choose the desired operating system 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Set up Python
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.x  # Replace with the desired Python version

    # - name: Execute Python Shell Script
    #  id : python
    #  run: 
    #    python ${{github.workspace}}'/.github/workflows/increment_version.py' "1.2.3"
    #    echo "RESULT=${{ steps.python.outputs.result }}" >> $GITHUB_ENV
    #    echo $RESULT
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.OKTA_CLIENT_ID }}
        aws-secret-access-key: ${{ secrets.OKTA_SECRET_ID }}
        aws-region: 'us-east-1'
        role-to-assume: "arn:aws:iam::753984600943:user/dharmateja"
        
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
      
